version: "3.9"

services:
  scraper:
    build: ./scraper_service
    container_name: fosil_scraper
    volumes:
      - ./data:/data
    restart: "no"

  data_processor:
    build: ./data_processing_service
    container_name: fosil_processor
    volumes:
      - ./data:/data
    depends_on:
      - scraper
    restart: "no"
